-- ============================================
--  Esquema PostgreSQL eco-tourism marketplace
--  (antes estaba en Oracle)
-- ============================================

-- =========================
-- TABLES
-- =========================

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(320),
    password        VARCHAR(255),
    name            VARCHAR(120),
    img_url         VARCHAR(500),
    active          SMALLINT DEFAULT 1,
    creation_date   DATE DEFAULT CURRENT_DATE,
    keycloak_user_id VARCHAR(200)
);

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50),
    description VARCHAR(255)
);

CREATE TABLE user_role (
    user_id BIGINT,
    role_id BIGINT
);

CREATE TABLE client (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT
);

CREATE TABLE provider (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    trade_name    VARCHAR(160),
    description   VARCHAR(2000),
    phone_number  VARCHAR(40),
    webpage       VARCHAR(500),
    creation_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE service_category (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120)
);

CREATE TABLE service (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id         BIGINT,
    service_categoryid  BIGINT,
    title               VARCHAR(160),
    description         VARCHAR(4000),
    price               NUMERIC(12,0),
    currency            CHAR(3),
    active              SMALLINT DEFAULT 1,
    creation_date       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    country_code        CHAR(3),
    city_code           CHAR(5),
    address             VARCHAR(400),
    start_date          TIMESTAMP(6),
    end_date            TIMESTAMP(6),
    transport_type      VARCHAR(50),
    route_origin        VARCHAR(400),
    route_destination   VARCHAR(400),
    latitude            NUMERIC(12,6),
    longitude           NUMERIC(12,6),
    country_info_json   TEXT,
    weather_info_json   TEXT
);

CREATE TABLE service_image (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT,
    url        VARCHAR(500),
    position   NUMERIC
);

CREATE TABLE social_network (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(80),
    url_base VARCHAR(200),
    icon     VARCHAR(120),
    active   SMALLINT DEFAULT 1
);

CREATE TABLE provider_social_network (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id       BIGINT,
    social_network_id BIGINT,
    url               VARCHAR(500)
);

CREATE TABLE service_cache (
    id     NUMERIC(19,0) PRIMARY KEY,
    title  VARCHAR(255),
    status VARCHAR(50)
);

CREATE TABLE provider_cache (
    id     NUMERIC(19,0) PRIMARY KEY,
    name   VARCHAR(255),
    status VARCHAR(50)
);

CREATE TABLE user_cache (
    id     NUMERIC(19,0) PRIMARY KEY,
    name   VARCHAR(255),
    status VARCHAR(50)
);

CREATE TABLE question (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id    BIGINT,
    user_id       BIGINT,
    text          VARCHAR(4000),
    creation_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE answer (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    question_id   BIGINT,
    text          VARCHAR(4000),
    creation_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE review (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id    BIGINT,
    user_id       BIGINT,
    stars         SMALLINT,
    comment_text  VARCHAR(4000),
    creation_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE cart (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    creation_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT,
    service_id BIGINT,
    quantity   NUMERIC,
    date_added TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id       BIGINT,
    user_id       BIGINT,
    order_date    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    status        VARCHAR(50),
    total_amount  NUMERIC(10,2),
    payment_method VARCHAR(60)
);

CREATE TABLE order_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT,
    service_id BIGINT,
    quantity   NUMERIC(10,0),
    price      NUMERIC(12,2)
);

CREATE TABLE payment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT,
    cart_id     BIGINT,
    user_id     BIGINT,
    total       NUMERIC(15,2),
    status      VARCHAR(20),
    order_date  TIMESTAMP(6),
    method      VARCHAR(20),
    transaction_id VARCHAR(100)
);

CREATE TABLE payment_detail (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT,
    quantity   NUMERIC,
    price      NUMERIC(15,2),
    payment_id BIGINT
);

CREATE TABLE receipt (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number VARCHAR(100),
    generated_at   TIMESTAMP(6),
    total          NUMERIC(15,2),
    payment_id     BIGINT
);

-- =========================
--  CONSTRAINTS (CHECK + UNIQUE)
-- =========================

ALTER TABLE review
  ADD CONSTRAINT ck_review_stars CHECK (stars BETWEEN 1 AND 5);

ALTER TABLE service
  ADD CONSTRAINT ck_service_active CHECK (active IN (0,1));

ALTER TABLE service
  ADD CONSTRAINT ck_service_ccy_len CHECK (char_length(currency) = 3);

ALTER TABLE social_network
  ADD CONSTRAINT ck_social_network_active CHECK (active IN (0,1));

ALTER TABLE users
  ADD CONSTRAINT ck_users_active CHECK (active IN (0,1));

-- Unique constraints

ALTER TABLE users
  ADD CONSTRAINT uq_user_email UNIQUE (email);

ALTER TABLE roles
  ADD CONSTRAINT uq_role_name UNIQUE (name);

ALTER TABLE social_network
  ADD CONSTRAINT uq_social_network_name UNIQUE (name);

ALTER TABLE review
  ADD CONSTRAINT uq_review_service_user UNIQUE (service_id, user_id);

ALTER TABLE service_category
  ADD CONSTRAINT uq_service_category_name UNIQUE (name);

ALTER TABLE client
  ADD CONSTRAINT uq_client_user UNIQUE (user_id);

ALTER TABLE provider
  ADD CONSTRAINT uq_provider_user UNIQUE (user_id);

ALTER TABLE provider_social_network
  ADD CONSTRAINT uq_psn_provider_socnet UNIQUE (provider_id, social_network_id);

ALTER TABLE receipt
  ADD CONSTRAINT uq_receipt_number UNIQUE (receipt_number);

ALTER TABLE receipt
  ADD CONSTRAINT uq_receipt_payment UNIQUE (payment_id);

-- =========================
--  FOREIGN KEYS
-- =========================

-- USER_ROLE
ALTER TABLE user_role
  ADD CONSTRAINT fk_user_role_user
  FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_role
  ADD CONSTRAINT fk_user_role_role
  FOREIGN KEY (role_id) REFERENCES roles (id);

-- CLIENT
ALTER TABLE client
  ADD CONSTRAINT fk_client_user
  FOREIGN KEY (user_id) REFERENCES users (id);

-- PROVIDER
ALTER TABLE provider
  ADD CONSTRAINT fk_provider_user
  FOREIGN KEY (user_id) REFERENCES users (id);

-- SERVICE
ALTER TABLE service
  ADD CONSTRAINT fk_service_provider
  FOREIGN KEY (provider_id) REFERENCES provider (id);

ALTER TABLE service
  ADD CONSTRAINT fk_service_category
  FOREIGN KEY (service_categoryid) REFERENCES service_category (id);

-- SERVICE_IMAGE
ALTER TABLE service_image
  ADD CONSTRAINT fk_service_images_service
  FOREIGN KEY (service_id) REFERENCES service (id);

-- PROVIDER_SOCIAL_NETWORK
ALTER TABLE provider_social_network
  ADD CONSTRAINT fk_psn_provider
  FOREIGN KEY (provider_id) REFERENCES provider (id);

ALTER TABLE provider_social_network
  ADD CONSTRAINT fk_psn_socnet
  FOREIGN KEY (social_network_id) REFERENCES social_network (id);

-- QUESTION
ALTER TABLE question
  ADD CONSTRAINT fk_question_service
  FOREIGN KEY (service_id) REFERENCES service (id);

ALTER TABLE question
  ADD CONSTRAINT fk_question_user
  FOREIGN KEY (user_id) REFERENCES users (id);

-- ANSWER
ALTER TABLE answer
  ADD CONSTRAINT fk_answer_question
  FOREIGN KEY (question_id) REFERENCES question (id);

-- REVIEW
ALTER TABLE review
  ADD CONSTRAINT fk_review_service
  FOREIGN KEY (service_id) REFERENCES service (id);

ALTER TABLE review
  ADD CONSTRAINT fk_review_user
  FOREIGN KEY (user_id) REFERENCES users (id);

-- CART
-- (no FK hacía falta aquí excepto user_id si quieres:)
ALTER TABLE cart
  ADD CONSTRAINT fk_cart_user
  FOREIGN KEY (user_id) REFERENCES users (id);

-- CART_ITEM
ALTER TABLE cart_item
  ADD CONSTRAINT fk_cart_item_cart
  FOREIGN KEY (cart_id) REFERENCES cart (id);

-- ORDERS
ALTER TABLE orders
  ADD CONSTRAINT fk_orders_cart
  FOREIGN KEY (cart_id) REFERENCES cart (id);

-- ORDER_ITEM
ALTER TABLE order_item
  ADD CONSTRAINT fk_orderitem_order
  FOREIGN KEY (order_id) REFERENCES orders (id);

-- PAYMENT_DETAIL
ALTER TABLE payment_detail
  ADD CONSTRAINT fk_payment_detail_payment
  FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE;

-- PAYMENT
ALTER TABLE payment
  ADD CONSTRAINT fk_payment_order
  FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE payment
  ADD CONSTRAINT fk_payment_cart
  FOREIGN KEY (cart_id) REFERENCES cart(id);

ALTER TABLE payment
  ADD CONSTRAINT fk_payment_user
  FOREIGN KEY (user_id) REFERENCES users(id);



-- RECEIPT
ALTER TABLE receipt
  ADD CONSTRAINT fk_receipt_payment
  FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE;
