spring:
  application:
    name: payment-service
  cloud:
      stream:
        kafka:
          binder:
            # 9092 is the default port of Kafka
            brokers: ${KAFKA_BOOTSTRAP_SERVERS:2.tcp.ngrok.io:17669}
            configuration:
              acks: all                      
              enable.idempotence: true  
        bindings:
          # https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/functional-binding-names.html
          # Format: <method name>-<in or out>-<index>
          # sendMessage: name of the method that sends the message
          # out: because is a producer
          # 0: Index of the binding. This makes sense when the same method sends to multiple queues
          paymentsRequest-out-0:
            destination: payments.request  
spring.config.import: "configserver:http://localhost:8888"
