# Variables globales
@host = http://184.72.84.92:8080/service-catalog
@keycloak_host = https://e73d150e7cc3.ngrok-free.app
@user = proveedor-prueba@example.com
@pass = 123
@client_id = gateway-client

### 1. Obtener token de Keycloak
# @name login
POST {{keycloak_host}}/realms/marketplace-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_id}}&username={{user}}&password={{pass}}

### Asignar variable auth_token automáticamente
@auth_token = {{login.response.body.$.access_token}}


# ============================================================
# 2. CREAR CATEGORÍAS PARA PRUEBAS
# ============================================================

### Alojamiento
POST {{host}}/categories
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Alojamiento"
}

### Transporte
POST {{host}}/categories
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Transporte"
}

### Servicio General
POST {{host}}/categories
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Servicios Generales"
}

###############################################
### 5. CREAR SERVICIO ALOJAMIENTO (Cat 1)
### Prueba: Google Geocoding + Weather + RestCountries
###############################################
POST {{host}}/services
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "providerId": 2,
  "categoryId": 1,
  "title": "Hotel Casa Bonita",
  "description": "Habitación confortable",
  "price": 120.0,
  "currency": "USD",
  "active": true,
  "countryCode": "COL",
  "cityCode": "BOG",

  "startDate": "2025-01-20T00:00:00",
  "endDate": "2025-01-25T00:00:00",

  "transportType": null,
  "routeOrigin": null,
  "routeDestination": null,

  "address": "Cra 7 # 32-16 Bogotá",
  "latitude": null,
  "longitude": null,

  "images": [
    { "url": "http://example.com/hotel1.jpg", "position": 1 }
  ]
}



###############################################
### 6. OBTENER SERVICIO ALOJAMIENTO (ID 1)
### Validar conexión a Google Maps + Weather + País
###############################################
GET {{host}}/services/4
Authorization: Bearer {{auth_token}}
Content-Type: application/json



###############################################
### 7. CREAR SERVICIO TRANSPORTE (Cat 2)
### Prueba: Google Directions + Weather + RestCountries
###############################################
POST {{host}}/services
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "providerId": 2,
  "categoryId": 6,
  "title": "Transporte Aeropuerto",
  "description": "Ruta aeropuerto -> hotel",
  "price": 40.0,
  "currency": "USD",
  "active": true,
  "countryCode": "COL",
  "cityCode": "BOG",

  "startDate": null,
  "endDate": null,

  "transportType": "terrestre",
  "routeOrigin": "Aeropuerto El Dorado, Bogotá, Colombia",
  "routeDestination": "Hotel Tequendama, Bogotá, Colombia",

  "address": null,
  "latitude": null,
  "longitude": null,

  "images": [
    { "url": "http://example.com/car1.jpg", "position": 1 }
  ]
}



###############################################
### 8. OBTENER SERVICIO TRANSPORTE (ID 2)
### Valida Google Directions + Weather
###############################################
GET {{host}}/services/3
Authorization: Bearer {{auth_token}}
Content-Type: application/json




