spring:
  datasource:
    url: ${spring_datasource_url}
    username: ${spring_datasource_username}
    password: ${spring_datasource_password}
    driver-class-name: ${spring_datasource_driver_class_name}

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

keycloak:
  server-url: https://e73d150e7cc3.ngrok-free.app
  realm: marketplace-realm
  client-id: admin-cli
  client-secret: ""
  username: admin
  password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  company:
    name: eco-tourism-marketplace
