server:
    port: 8084

info:
    app:
      name: Payment Microservice
      description: A microservice for Payment funcionalities
      version: 1.0.0
    company:
      name: eco-tourism-marketplace
    build:
      time: ${BUILD_TIME:2024-09-19T12:30:00Z}